BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS DetailRow (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Details TEXT NOT NULL,
    Value TEXT NOT NULL,
    Status TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ChannelRow (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Channel TEXT NOT NULL,
    Name TEXT NOT NULL,
    Status TEXT NOT NULL
);

COMMIT; 